### ISSUE TITLE
Найти и проанализировать датасет для обучения модели определния возраста

### ISSUE THREAD

**Issue by Martulik** [KateBor/age-detection#1]

**Comment by DariaDiurdeva** [comment]
Датасет https://www.kaggle.com/datasets/ttungl/adience-benchmark-gender-and-age-classification/data
В папке faces находятся подпапки с id юзера, а в подпапке разные фотки юзер. 
5 файлов fold, в которых данные имеют следующий формат
<img width="1004" alt="Снимок экрана 2024-03-01 в 21 36 37" src="https://github.com/KateBor/age-detection/assets/59419814/de8dd3fa-4c1b-4f64-aaa0-ca20912aa07d">

**Comment by DariaDiurdeva** [comment]
Для реализации был выбран датасет APPA-REAL, содержащий 7 591 изображение с соответствующими метками реального возраста. Изначально база данных APPA-REAL содержит 7 591 изображение с соответствующими метками реального и видимого возраста. Общее количество видимых голосов составляет около 250 000. В среднем по 38 голосов на каждое изображение, что делает средний видимый возраст очень стабильным (стандартная ошибка среднего 0,3).  Однако, поскольку основной целью является предсказание реального возраста, который был четко помечен в датасете, исключение видимого возраста из модели может помочь улучшить точность прогнозирования и сделать модель более надежной и точной. Поэтому будем исопользовать заранее подготовленный датасет имеющий данные только о реальном возрасте: ссылка на dataset https://www.kaggle.com/datasets/abhikjha/appa-real-face-cropped/data .

Датасет содержит: 
1) папка со всеми изображениями /final_files
2) CSV-файл labels.csv с двумя колонками: file_name - имя файла с изображением и real_age - реальный возраст человека на фото.

[В статье о датасете](http://people.ee.ethz.ch/~timofter/publications/Agustsson-FG-2017.pdf), с которым мы имеем дело, значение MAE на реальном возрасте равно 5.4. Поэтому будем считать, что значение mae до 7 будет хорошим резульататом. 

**Результаты анализа датасета:**

![image](https://github.com/KateBor/age-detection/assets/59419814/e7f0eff3-70db-476f-8b20-6268e8dfabcc)

![image](https://github.com/KateBor/age-detection/assets/59419814/8a2b6468-2ef4-4e62-a122-9a8989f5c35b)

1) Пропусков данных нет.
2) Дублей нет.
3) Информация о возрасте имеет следующие характеристики: минимальный возраст 1 год, максимальный - 100 лет, средний возраст 31 год, медианный - 29 лет. Визуально, возраст людей на фотографиях, соотвествует указанному возрасту в датасете.
4) Распределение объектов по возрасту не равномерное и напоминает по форме распределение Пуассона и похоже на распределение возраста в естественной популяции, со средним значением 31.2 и стандартным отклонением 17.14, при этом 95% значений лежат в диапазоне до 2 лет до 71 года. Наибольшее число данных приходится на диапазон возрастов от 20 до 59 лет. Меньше всего фотографий людей от 60 лет и старше поэтому можно предположить что значения ошибки на изображениях лиц пожилых людей будет больше.

Таким образом мы имеем достаточно не большой и разбалансированный набор данных и это может негативным образом отразится на обучении модели и качестве её работы. _Сначала попробуем обучить модель без дополнительных манипуляций с датасетом, если значения mae будет выше 7, то для снижения дисбаланса можно использовать технику аугментации изображений редко представленных возрастных групп._
